spring:
  application:
    name: enterprise-asset-tokenization

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tokenization}
    username: ${SPRING_DATASOURCE_USERNAME:tokenization_user}
    password: ${SPRING_DATASOURCE_PASSWORD:change_me_in_production}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

# Blockchain Configuration
blockchain:
  besu:
    rpc-url: ${BESU_RPC_URL:http://localhost:8545}
    ws-url: ${BESU_WS_URL:ws://localhost:8546}
    chain-id: ${BESU_CHAIN_ID:1337}
    gas-price: 0
    gas-limit: 6721975
  contract:
    asset-token-address: ${ASSET_TOKEN_CONTRACT_ADDRESS:}
  wallet:
    private-key: ${DEPLOYER_PRIVATE_KEY:}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  issuer: enterprise-tokenization-platform

# Logging Configuration
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.enterprise.tokenization: ${LOGGING_LEVEL_COM_ENTERPRISE_TOKENIZATION:DEBUG}
    org.springframework.web: INFO
    org.hibernate: INFO
    org.web3j: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha